<?php if (count($this->tests)): ?>

    <table class="table table-striped">
        <thead>
            <tr>
                <th><?= $this->translate('Name') ?></th>
                <th><?= $this->translate('Description') ?></th>
                <th><?= $this->translate('Duration') ?></th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->tests as $test): ?>
                <tr>
                    <td>
                        <a href="<?php
                        echo
                            $this->url('exam/default', array(
                                'controller'=> 'test',
                                'action'    => 'take',
                                'id'        => $test->id
                            ));?>">
                        <?= $test->name ?>
                        </a>
                    </td>
                    <td><?= $test->description ?></td>
                    <td><?= $test->duration ?></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<?php
    echo $this->paginationControl(
        $this->tests,
        'Sliding',
        'paginator/sliding',
        array('route' => 'exam/list')
    );