<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php

                        $navHelper = $this->navigation('navigation');
                        $containers = $navHelper->getContainer();

                        foreach($containers->getPages() as $page) {

                            $class = "";
                            if($page->isActive()) {
                                $class = "active";
                            }

                            if(count($page)) {
                                // if there are subpages we render the menu a bit different
                                $label = $page->getLabel();
                                $label = $this->translate($label); // translated label
                                $label = $this->escapehtml($label); // sanitized label
                                printf('<li class="dropdown%s">' . "\n",
                                    ($class ? (' ' . $class) : '')
                                );
                                printf(' <a href="%s" class="dropdown-toggle" data-toggle="dropdown">%s<b class="caret"></b></a>' . "\n",
                                    $page->getHref(),
                                    $label
                                );
                                echo '<ul class="dropdown-menu">' . "\n";
                                foreach($page as $subPage) {
                                    if (!$navHelper->accept($subPage)) {
                                        continue;
                                    }
                                    printf("<li>%s</li>\n",
                                        $navHelper->htmlify($subPage)
                                    );
                                }
                                echo "</ul></li>\n";

                            } else {
                                printf("<li class=\"%s\">%s</li>\n",
                                    $class,
                                    $navHelper->htmlify($page)
                                );
                            }

                        }

                        ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="breadcrumb">
            <!-- Breadcrumb navigation -->
            <?php

            echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(1)->setSeparator('&#10151;' . PHP_EOL);

            ?>
        </div>

        <?php

        $namespaces = array('error', 'success', 'info', 'default');
        foreach ($namespaces as $namespace) {
            $flashMessages = $this->flashMessenger()->renderCurrent($namespace);
            if (!empty($flashMessages)) {
                ?>
                <div id="myAlert" class="alert alert-<?= $namespace ?>" data-alert="alert">
                    <a class="close" data-dismiss="alert">x</a>
                    <?= $flashMessages ?>
                </div>
            <?php
            }
        }

        ?>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
