<h1>Top line</h1>
<?= $this->content ?>

<h1>Bottom line</h1>
<?php
if($this->profiler) {
    echo '<div id="profiler">Db Profiler:';
    foreach($this->profiler->getProfiles() as $profile) {
        echo '"' . $profile['sql'] . 
                '(' . 
                implode(',', $profile['parameters']->getNamedArray()) . 
                ')" took ' .
                $profile['elapse'] . ' seconds<br>';
        echo '</div>';
    }
}