<h1>Top line</h1>
<?= $this->content ?>

<h1>Bottom line</h1>
<?php
if($this->profiler) {
    echo '<div id="profiler">Db Profiler:<br />';
    foreach($this->profiler->getProfiles() as $profile) {
        echo '"' . $profile['sql'] .
                '(' .
                implode(',', $profile['parameters']->getNamedArray()) .
                ')" took ' .
                $profile['elapse'] . ' seconds' . "<br />\n";
        echo '</div>';
    }
}

if(isset($this->cache)) {
    echo '<div id="cache"><br />Cache hits:<br />';
    foreach($this->cache->hits as $key => $count) {
        echo "$key => $count<br />\n";
    }
    echo '</div>';
}
